/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_innovatec;

/**
 *
 * @author Fernando Sosa
 */
public class GeneralMenu extends javax.swing.JFrame {

    /**
     * Creates new form GeneralMenu
     */
    public GeneralMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Login = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Crear_Pacientes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paciente_nombre_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        paciente_telefono_field = new javax.swing.JTextField();
        boton_regresar = new javax.swing.JButton();
        boton_registrar_paciente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        paciente_apellido_field = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        paciente_identidad_field = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        paciente_genero_combo_box = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        paciente_dia_field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        paciente_mes_field = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        paciente_mes_field1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        paciente_edad_field = new javax.swing.JTextField();
        Crear_Consultas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Consultas_expediente_field = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Consultas_id_consultas_field = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Consultas_ordenes_field = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Consultas_motivo_field = new javax.swing.JTextField();
        boton_regresar1 = new javax.swing.JButton();
        boton_registro_consulta = new javax.swing.JButton();
        Crear_Examenes = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Examen_expediente_field = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Examen_id_consultas_field = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Examen_id_archivo_field = new javax.swing.JTextField();
        boton_regresar2 = new javax.swing.JButton();
        boton_regresar3 = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        boton_crear_pacientes = new javax.swing.JButton();
        boton_crear_Consultas = new javax.swing.JButton();
        boton_crear_Examenes = new javax.swing.JButton();
        boton_busqueda = new javax.swing.JButton();
        boton_regreso_login = new javax.swing.JButton();
        Busqueda = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        Busqueda_id_consultas_field = new javax.swing.JTextField();
        boton_regresar4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        Busqueda_id_examenes_field = new javax.swing.JTextField();
        boton_regresar5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        Busqueda_id_pacientes_field = new javax.swing.JTextField();
        boton_regresar6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(28, 158, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CENTRO");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 95, 106));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MEJIA");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MEDICO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(104, 104, 104))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Ingrese sus datos");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Nombre");

        jTextField1.setBackground(new java.awt.Color(28, 158, 153));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Ingresar nombre");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Contraseña");

        jPasswordField1.setBackground(new java.awt.Color(28, 158, 153));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setActionCommand("<Not Set>");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(28, 158, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ingresar");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BIENVENIDO");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jButton1)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addGap(46, 46, 46)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("tab1", Login);

        Crear_Pacientes.setBackground(new java.awt.Color(28, 158, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Creacion de Pacientes");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nombre");

        paciente_nombre_field.setBackground(new java.awt.Color(28, 158, 153));
        paciente_nombre_field.setForeground(new java.awt.Color(255, 255, 255));
        paciente_nombre_field.setText("Ingrese nombre del paciente");
        paciente_nombre_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                paciente_nombre_fieldFocusLost(evt);
            }
        });
        paciente_nombre_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_nombre_fieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Telefono");

        paciente_telefono_field.setBackground(new java.awt.Color(28, 158, 153));
        paciente_telefono_field.setForeground(new java.awt.Color(255, 255, 255));
        paciente_telefono_field.setText("Ingrese numero de telefono");
        paciente_telefono_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                paciente_telefono_fieldFocusLost(evt);
            }
        });
        paciente_telefono_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_telefono_fieldActionPerformed(evt);
            }
        });

        boton_regresar.setBackground(new java.awt.Color(28, 158, 153));
        boton_regresar.setForeground(new java.awt.Color(255, 255, 255));
        boton_regresar.setText("Regresar");

        boton_registrar_paciente.setBackground(new java.awt.Color(28, 158, 153));
        boton_registrar_paciente.setForeground(new java.awt.Color(255, 255, 255));
        boton_registrar_paciente.setText("Registrar Paciente");
        boton_registrar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrar_pacienteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("/");

        paciente_apellido_field.setBackground(new java.awt.Color(28, 158, 153));
        paciente_apellido_field.setForeground(new java.awt.Color(255, 255, 255));
        paciente_apellido_field.setText("Ingrese apellido del paciente");
        paciente_apellido_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                paciente_apellido_fieldFocusLost(evt);
            }
        });
        paciente_apellido_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_apellido_fieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Identidad");

        paciente_identidad_field.setBackground(new java.awt.Color(28, 158, 153));
        paciente_identidad_field.setForeground(new java.awt.Color(255, 255, 255));
        paciente_identidad_field.setText("Ingrese identidad del paciente");
        paciente_identidad_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                paciente_identidad_fieldFocusLost(evt);
            }
        });
        paciente_identidad_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_identidad_fieldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Genero");

        paciente_genero_combo_box.setBackground(new java.awt.Color(28, 158, 153));
        paciente_genero_combo_box.setForeground(new java.awt.Color(255, 255, 255));
        paciente_genero_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        paciente_genero_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_genero_combo_boxActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Fecha de Nacimiento");

        paciente_dia_field.setBackground(new java.awt.Color(28, 158, 153));
        paciente_dia_field.setForeground(new java.awt.Color(255, 255, 255));
        paciente_dia_field.setText("12");
        paciente_dia_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_dia_fieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Apellido");

        paciente_mes_field.setBackground(new java.awt.Color(28, 158, 153));
        paciente_mes_field.setForeground(new java.awt.Color(255, 255, 255));
        paciente_mes_field.setText("12");
        paciente_mes_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_mes_fieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("/");

        paciente_mes_field1.setBackground(new java.awt.Color(28, 158, 153));
        paciente_mes_field1.setForeground(new java.awt.Color(255, 255, 255));
        paciente_mes_field1.setText("2023");
        paciente_mes_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_mes_field1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Fecha de Nacimiento");

        paciente_edad_field.setBackground(new java.awt.Color(28, 158, 153));
        paciente_edad_field.setForeground(new java.awt.Color(255, 255, 255));
        paciente_edad_field.setText("Ingrese edad del paciente");
        paciente_edad_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                paciente_edad_fieldFocusLost(evt);
            }
        });
        paciente_edad_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_edad_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paciente_nombre_field)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paciente_identidad_field)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paciente_genero_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paciente_edad_field))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paciente_apellido_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paciente_telefono_field, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(paciente_dia_field, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(9, 9, 9)
                                .addComponent(paciente_mes_field, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paciente_mes_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(boton_regresar)
                        .addGap(169, 169, 169)
                        .addComponent(boton_registrar_paciente)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paciente_nombre_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paciente_apellido_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paciente_telefono_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paciente_identidad_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paciente_genero_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paciente_dia_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paciente_mes_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paciente_mes_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paciente_edad_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_regresar)
                    .addComponent(boton_registrar_paciente))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout Crear_PacientesLayout = new javax.swing.GroupLayout(Crear_Pacientes);
        Crear_Pacientes.setLayout(Crear_PacientesLayout);
        Crear_PacientesLayout.setHorizontalGroup(
            Crear_PacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_PacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Crear_PacientesLayout.setVerticalGroup(
            Crear_PacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_PacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", Crear_Pacientes);

        Crear_Consultas.setBackground(new java.awt.Color(28, 158, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Creacion de Consultas");

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Ordenes Medicas");

        Consultas_expediente_field.setBackground(new java.awt.Color(28, 158, 153));
        Consultas_expediente_field.setForeground(new java.awt.Color(255, 255, 255));
        Consultas_expediente_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Consultas_expediente_fieldFocusLost(evt);
            }
        });
        Consultas_expediente_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultas_expediente_fieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Id Consulta");

        Consultas_id_consultas_field.setBackground(new java.awt.Color(28, 158, 153));
        Consultas_id_consultas_field.setForeground(new java.awt.Color(255, 255, 255));
        Consultas_id_consultas_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Consultas_id_consultas_fieldFocusLost(evt);
            }
        });
        Consultas_id_consultas_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultas_id_consultas_fieldActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Numero de expediente");

        Consultas_ordenes_field.setBackground(new java.awt.Color(28, 158, 153));
        Consultas_ordenes_field.setForeground(new java.awt.Color(255, 255, 255));
        Consultas_ordenes_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Consultas_ordenes_fieldFocusLost(evt);
            }
        });
        Consultas_ordenes_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultas_ordenes_fieldActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Motivo de Consulta");

        Consultas_motivo_field.setBackground(new java.awt.Color(28, 158, 153));
        Consultas_motivo_field.setForeground(new java.awt.Color(255, 255, 255));
        Consultas_motivo_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Consultas_motivo_fieldFocusLost(evt);
            }
        });
        Consultas_motivo_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultas_motivo_fieldActionPerformed(evt);
            }
        });

        boton_regresar1.setBackground(new java.awt.Color(28, 158, 153));
        boton_regresar1.setForeground(new java.awt.Color(255, 255, 255));
        boton_regresar1.setText("Regresar");

        boton_registro_consulta.setBackground(new java.awt.Color(28, 158, 153));
        boton_registro_consulta.setForeground(new java.awt.Color(255, 255, 255));
        boton_registro_consulta.setText("Registrar Consulta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(Consultas_expediente_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Consultas_id_consultas_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addComponent(jLabel19)
                            .addComponent(Consultas_ordenes_field, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Consultas_motivo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(boton_regresar1)
                        .addGap(191, 191, 191)
                        .addComponent(boton_registro_consulta)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultas_expediente_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consultas_id_consultas_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Consultas_motivo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Consultas_ordenes_field, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_regresar1)
                    .addComponent(boton_registro_consulta))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout Crear_ConsultasLayout = new javax.swing.GroupLayout(Crear_Consultas);
        Crear_Consultas.setLayout(Crear_ConsultasLayout);
        Crear_ConsultasLayout.setHorizontalGroup(
            Crear_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_ConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Crear_ConsultasLayout.setVerticalGroup(
            Crear_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_ConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", Crear_Consultas);

        Crear_Examenes.setBackground(new java.awt.Color(28, 158, 153));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Creacion de Examenes");

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Numero de expediente");

        Examen_expediente_field.setBackground(new java.awt.Color(28, 158, 153));
        Examen_expediente_field.setForeground(new java.awt.Color(255, 255, 255));
        Examen_expediente_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Examen_expediente_fieldFocusLost(evt);
            }
        });
        Examen_expediente_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Examen_expediente_fieldActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Id Consulta");

        Examen_id_consultas_field.setBackground(new java.awt.Color(28, 158, 153));
        Examen_id_consultas_field.setForeground(new java.awt.Color(255, 255, 255));
        Examen_id_consultas_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Examen_id_consultas_fieldFocusLost(evt);
            }
        });
        Examen_id_consultas_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Examen_id_consultas_fieldActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Id Archivo");

        Examen_id_archivo_field.setBackground(new java.awt.Color(28, 158, 153));
        Examen_id_archivo_field.setForeground(new java.awt.Color(255, 255, 255));
        Examen_id_archivo_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Examen_id_archivo_fieldFocusLost(evt);
            }
        });
        Examen_id_archivo_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Examen_id_archivo_fieldActionPerformed(evt);
            }
        });

        boton_regresar2.setBackground(new java.awt.Color(28, 158, 153));
        boton_regresar2.setForeground(new java.awt.Color(255, 255, 255));
        boton_regresar2.setText("Regresar");

        boton_regresar3.setBackground(new java.awt.Color(28, 158, 153));
        boton_regresar3.setForeground(new java.awt.Color(255, 255, 255));
        boton_regresar3.setText("Registrar Examen");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Examen_id_archivo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(Examen_expediente_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Examen_id_consultas_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boton_regresar2))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(boton_regresar3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel23)
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Examen_expediente_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Examen_id_consultas_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Examen_id_archivo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(boton_regresar3)
                .addGap(18, 18, 18)
                .addComponent(boton_regresar2)
                .addContainerGap())
        );

        javax.swing.GroupLayout Crear_ExamenesLayout = new javax.swing.GroupLayout(Crear_Examenes);
        Crear_Examenes.setLayout(Crear_ExamenesLayout);
        Crear_ExamenesLayout.setHorizontalGroup(
            Crear_ExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_ExamenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Crear_ExamenesLayout.setVerticalGroup(
            Crear_ExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_ExamenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab4", Crear_Examenes);

        Menu.setBackground(new java.awt.Color(28, 158, 153));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Menu");

        boton_crear_pacientes.setBackground(new java.awt.Color(28, 158, 153));
        boton_crear_pacientes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        boton_crear_pacientes.setForeground(new java.awt.Color(255, 255, 255));
        boton_crear_pacientes.setText("Crear Paciente");
        boton_crear_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crear_pacientesActionPerformed(evt);
            }
        });

        boton_crear_Consultas.setBackground(new java.awt.Color(28, 158, 153));
        boton_crear_Consultas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        boton_crear_Consultas.setForeground(new java.awt.Color(255, 255, 255));
        boton_crear_Consultas.setText("Crear Consultas");
        boton_crear_Consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crear_ConsultasActionPerformed(evt);
            }
        });

        boton_crear_Examenes.setBackground(new java.awt.Color(28, 158, 153));
        boton_crear_Examenes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        boton_crear_Examenes.setForeground(new java.awt.Color(255, 255, 255));
        boton_crear_Examenes.setText("Crear Examenes");
        boton_crear_Examenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crear_ExamenesActionPerformed(evt);
            }
        });

        boton_busqueda.setBackground(new java.awt.Color(28, 158, 153));
        boton_busqueda.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        boton_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        boton_busqueda.setText("Buscar");
        boton_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_busquedaActionPerformed(evt);
            }
        });

        boton_regreso_login.setBackground(new java.awt.Color(28, 158, 153));
        boton_regreso_login.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        boton_regreso_login.setForeground(new java.awt.Color(255, 255, 255));
        boton_regreso_login.setText("Regresar");
        boton_regreso_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_regreso_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_crear_Examenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_crear_Consultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_crear_pacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_busqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_regreso_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(30, 30, 30)
                .addComponent(boton_crear_pacientes)
                .addGap(32, 32, 32)
                .addComponent(boton_crear_Consultas)
                .addGap(36, 36, 36)
                .addComponent(boton_crear_Examenes)
                .addGap(33, 33, 33)
                .addComponent(boton_busqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(boton_regreso_login)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab5", Menu);

        Busqueda.setBackground(new java.awt.Color(28, 158, 153));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(28, 158, 153));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Ingrese el id de Consulta");

        Busqueda_id_consultas_field.setBackground(new java.awt.Color(28, 158, 153));
        Busqueda_id_consultas_field.setForeground(new java.awt.Color(255, 255, 255));
        Busqueda_id_consultas_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Busqueda_id_consultas_fieldFocusLost(evt);
            }
        });
        Busqueda_id_consultas_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda_id_consultas_fieldActionPerformed(evt);
            }
        });

        boton_regresar4.setBackground(new java.awt.Color(28, 158, 153));
        boton_regresar4.setForeground(new java.awt.Color(255, 255, 255));
        boton_regresar4.setText("Regresar");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(Busqueda_id_consultas_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_regresar4))
                .addContainerGap(505, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Busqueda_id_consultas_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(boton_regresar4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Consultas", jPanel5);

        jPanel8.setBackground(new java.awt.Color(28, 158, 153));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Ingrese el id de Examenes");

        Busqueda_id_examenes_field.setBackground(new java.awt.Color(28, 158, 153));
        Busqueda_id_examenes_field.setForeground(new java.awt.Color(255, 255, 255));
        Busqueda_id_examenes_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Busqueda_id_examenes_fieldFocusLost(evt);
            }
        });
        Busqueda_id_examenes_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda_id_examenes_fieldActionPerformed(evt);
            }
        });

        boton_regresar5.setBackground(new java.awt.Color(28, 158, 153));
        boton_regresar5.setForeground(new java.awt.Color(255, 255, 255));
        boton_regresar5.setText("Regresar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(Busqueda_id_examenes_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_regresar5))
                .addContainerGap(498, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Busqueda_id_examenes_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(boton_regresar5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Examenes", jPanel8);

        jPanel4.setBackground(new java.awt.Color(28, 158, 153));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Ingrese el id de Pacientes");

        Busqueda_id_pacientes_field.setBackground(new java.awt.Color(28, 158, 153));
        Busqueda_id_pacientes_field.setForeground(new java.awt.Color(255, 255, 255));
        Busqueda_id_pacientes_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Busqueda_id_pacientes_fieldFocusLost(evt);
            }
        });
        Busqueda_id_pacientes_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda_id_pacientes_fieldActionPerformed(evt);
            }
        });

        boton_regresar6.setBackground(new java.awt.Color(28, 158, 153));
        boton_regresar6.setForeground(new java.awt.Color(255, 255, 255));
        boton_regresar6.setText("Regresar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(Busqueda_id_pacientes_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_regresar6))
                .addContainerGap(501, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Busqueda_id_pacientes_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(boton_regresar6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Pacientes", jPanel4);

        javax.swing.GroupLayout BusquedaLayout = new javax.swing.GroupLayout(Busqueda);
        Busqueda.setLayout(BusquedaLayout);
        BusquedaLayout.setHorizontalGroup(
            BusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        BusquedaLayout.setVerticalGroup(
            BusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("tab6", Busqueda);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -38, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(this.jTextField1.getText().equals("")){
            this.jTextField1.setText("Ingrese Nombre del Paciente");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        if(this.jPasswordField1.getText().equals("Ingrese Contraseña")){
            this.jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        if(this.jPasswordField1.getText().equals("")){
            this.jPasswordField1.setText("Ingrese Contraseña");
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void paciente_nombre_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paciente_nombre_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_nombre_fieldFocusLost

    private void paciente_nombre_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_nombre_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_nombre_fieldActionPerformed

    private void paciente_telefono_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paciente_telefono_fieldFocusLost
        if(this.paciente_telefono_field.getText().equals("")){
            this.paciente_telefono_field.setText("Ingrese numero de telefono");
        }
    }//GEN-LAST:event_paciente_telefono_fieldFocusLost

    private void paciente_telefono_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_telefono_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_telefono_fieldActionPerformed

    private void boton_registrar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrar_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_registrar_pacienteActionPerformed

    private void paciente_apellido_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paciente_apellido_fieldFocusLost
        if(this.paciente_apellido_field.getText().equals("")){
            this.paciente_apellido_field.setText("Ingrese apellido del paciente");
        }
    }//GEN-LAST:event_paciente_apellido_fieldFocusLost

    private void paciente_apellido_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_apellido_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_apellido_fieldActionPerformed

    private void paciente_identidad_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paciente_identidad_fieldFocusLost
        if(this.paciente_identidad_field.getText().equals("")){
            this.paciente_identidad_field.setText("Ingrese identidad del paciente");
        }
    }//GEN-LAST:event_paciente_identidad_fieldFocusLost

    private void paciente_identidad_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_identidad_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_identidad_fieldActionPerformed

    private void paciente_genero_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_genero_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_genero_combo_boxActionPerformed

    private void paciente_dia_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_dia_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_dia_fieldActionPerformed

    private void paciente_mes_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_mes_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_mes_fieldActionPerformed

    private void paciente_mes_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_mes_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_mes_field1ActionPerformed

    private void paciente_edad_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paciente_edad_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_edad_fieldFocusLost

    private void paciente_edad_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_edad_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_edad_fieldActionPerformed

    private void Consultas_expediente_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Consultas_expediente_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_expediente_fieldFocusLost

    private void Consultas_expediente_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultas_expediente_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_expediente_fieldActionPerformed

    private void Consultas_id_consultas_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Consultas_id_consultas_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_id_consultas_fieldFocusLost

    private void Consultas_id_consultas_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultas_id_consultas_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_id_consultas_fieldActionPerformed

    private void Consultas_ordenes_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Consultas_ordenes_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_ordenes_fieldFocusLost

    private void Consultas_ordenes_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultas_ordenes_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_ordenes_fieldActionPerformed

    private void Consultas_motivo_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Consultas_motivo_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_motivo_fieldFocusLost

    private void Consultas_motivo_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultas_motivo_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_motivo_fieldActionPerformed

    private void Examen_expediente_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Examen_expediente_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Examen_expediente_fieldFocusLost

    private void Examen_expediente_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Examen_expediente_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Examen_expediente_fieldActionPerformed

    private void Examen_id_consultas_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Examen_id_consultas_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Examen_id_consultas_fieldFocusLost

    private void Examen_id_consultas_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Examen_id_consultas_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Examen_id_consultas_fieldActionPerformed

    private void Examen_id_archivo_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Examen_id_archivo_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Examen_id_archivo_fieldFocusLost

    private void Examen_id_archivo_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Examen_id_archivo_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Examen_id_archivo_fieldActionPerformed

    private void boton_crear_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crear_pacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_crear_pacientesActionPerformed

    private void boton_crear_ConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crear_ConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_crear_ConsultasActionPerformed

    private void boton_crear_ExamenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crear_ExamenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_crear_ExamenesActionPerformed

    private void boton_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_busquedaActionPerformed

    private void boton_regreso_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_regreso_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_regreso_loginActionPerformed

    private void Busqueda_id_consultas_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Busqueda_id_consultas_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Busqueda_id_consultas_fieldFocusLost

    private void Busqueda_id_consultas_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda_id_consultas_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Busqueda_id_consultas_fieldActionPerformed

    private void Busqueda_id_examenes_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Busqueda_id_examenes_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Busqueda_id_examenes_fieldFocusLost

    private void Busqueda_id_examenes_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda_id_examenes_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Busqueda_id_examenes_fieldActionPerformed

    private void Busqueda_id_pacientes_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Busqueda_id_pacientes_fieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Busqueda_id_pacientes_fieldFocusLost

    private void Busqueda_id_pacientes_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda_id_pacientes_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Busqueda_id_pacientes_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Busqueda;
    private javax.swing.JTextField Busqueda_id_consultas_field;
    private javax.swing.JTextField Busqueda_id_examenes_field;
    private javax.swing.JTextField Busqueda_id_pacientes_field;
    private javax.swing.JTextField Consultas_expediente_field;
    private javax.swing.JTextField Consultas_id_consultas_field;
    private javax.swing.JTextField Consultas_motivo_field;
    private javax.swing.JTextField Consultas_ordenes_field;
    private javax.swing.JPanel Crear_Consultas;
    private javax.swing.JPanel Crear_Examenes;
    private javax.swing.JPanel Crear_Pacientes;
    private javax.swing.JTextField Examen_expediente_field;
    private javax.swing.JTextField Examen_id_archivo_field;
    private javax.swing.JTextField Examen_id_consultas_field;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton boton_busqueda;
    private javax.swing.JButton boton_crear_Consultas;
    private javax.swing.JButton boton_crear_Examenes;
    private javax.swing.JButton boton_crear_pacientes;
    private javax.swing.JButton boton_registrar_paciente;
    private javax.swing.JButton boton_registro_consulta;
    private javax.swing.JButton boton_regresar;
    private javax.swing.JButton boton_regresar1;
    private javax.swing.JButton boton_regresar2;
    private javax.swing.JButton boton_regresar3;
    private javax.swing.JButton boton_regresar4;
    private javax.swing.JButton boton_regresar5;
    private javax.swing.JButton boton_regresar6;
    private javax.swing.JButton boton_regreso_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField paciente_apellido_field;
    private javax.swing.JTextField paciente_dia_field;
    private javax.swing.JTextField paciente_edad_field;
    private javax.swing.JComboBox<String> paciente_genero_combo_box;
    private javax.swing.JTextField paciente_identidad_field;
    private javax.swing.JTextField paciente_mes_field;
    private javax.swing.JTextField paciente_mes_field1;
    private javax.swing.JTextField paciente_nombre_field;
    private javax.swing.JTextField paciente_telefono_field;
    // End of variables declaration//GEN-END:variables
}
